- 
  name: docker installation
  hosts: [servers]
  vars:
    proxy: <proxy_url>
    turn_On_Sanction: true
    ansible_python_interpreter: /usr/bin/python3
  become: true
  roles: 
    - role: sanction
      when: turn_On_Sanction 
    - docker
    - docker_compose
