- name: Install docker-compose
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.27.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '+x'

- name: remove sanction
  lineinfile: 
    dest: /etc/resolv.conf
    state: absent
    line: "{{dns}}"
  when: turn_On_Sanction 
